sonar.projectKey=sistema-donaciones
sonar.projectName=Sistema de Gestion de Donaciones
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=reports/pytest/coverage.xml
sonar.exclusions=**/__pycache__/**,**/reports/**

